### ISSUE TITLE
Components for Azalea / GreatFET One

### ISSUE THREAD

**Issue by xairy** [greatscottgadgets/greatfet#149]
Hi!

Could you post a list of components required to build an Azalea / GreatFET One board somewhere (wiki?)? If it comes in a form of DigiKey links that would be perfect.

Thanks!

**Comment by dominicgs** [comment]
Hi,

We tend to be wary of putting component lists up because they become stale as the project changes over time (e.g. components EOLd, etc).

It's fairly straight forward to export a list of parts from the schematic view in KiCad.  The design files for GreatFET arein the [greatfet-hardware](https://github.com/greatscottgadgets/greatfet-hardware) repository.  the main board is known as Azalea.
